### ISSUE TITLE
Change the buttons in the initial form and allow for more in depth probing

### ISSUE THREAD

**Issue by ishansheth-31** [ishansheth-31/breezy_frontend#2]
meds, surgeries, and any drug allergies (whatever the button questions are)

**Comment by tylerrcady** [comment]
Pushing due date a few days since worked on refactoring/redesigning front-end first

**Comment by tylerrcady** [comment]
Finished, however, just formatted the JSON input as a string for now, since backend gave errors with JSONs, something to change going forward.
